// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/app.dart';
import 'api/backup.dart';
import 'api/endpoints.dart';
import 'api/error.dart';
import 'api/history.dart';
import 'api/mempool.dart';
import 'api/names.dart';
import 'api/price.dart';
import 'api/proposals.dart';
import 'api/received.dart';
import 'api/relay_log.dart';
import 'api/repair.dart';
import 'api/spends.dart';
import 'api/tor.dart';
import 'api/vault.dart';
import 'api/watch.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<MempoolEvent> dco_decode_StreamSink_mempool_event_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<SendProgress> dco_decode_StreamSink_send_progress_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<VaultActivity> dco_decode_StreamSink_vault_activity_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AddressCheck dco_decode_address_check(dynamic raw);

  @protected
  ApproveResult dco_decode_approve_result(dynamic raw);

  @protected
  Balance dco_decode_balance(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  ZafeError dco_decode_box_autoadd_zafe_error(dynamic raw);

  @protected
  ExportedBackup dco_decode_exported_backup(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  IdentityInfo dco_decode_identity_info(dynamic raw);

  @protected
  ImportedVault dco_decode_imported_vault(dynamic raw);

  @protected
  InviteInfo dco_decode_invite_info(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<PaymentInfo> dco_decode_list_payment_info(dynamic raw);

  @protected
  List<PaymentInput> dco_decode_list_payment_input(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ProposalInfo> dco_decode_list_proposal_info(dynamic raw);

  @protected
  List<ReceivedInfo> dco_decode_list_received_info(dynamic raw);

  @protected
  List<RepairInfo> dco_decode_list_repair_info(dynamic raw);

  @protected
  List<ScannedPayment> dco_decode_list_scanned_payment(dynamic raw);

  @protected
  List<SeatMove> dco_decode_list_seat_move(dynamic raw);

  @protected
  List<SignerName> dco_decode_list_signer_name(dynamic raw);

  @protected
  List<UnapprovedSpendInfo> dco_decode_list_unapproved_spend_info(dynamic raw);

  @protected
  MembershipInfo dco_decode_membership_info(dynamic raw);

  @protected
  MempoolEvent dco_decode_mempool_event(dynamic raw);

  @protected
  MempoolStatus dco_decode_mempool_status(dynamic raw);

  @protected
  MyVote dco_decode_my_vote(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  ZafeError? dco_decode_opt_box_autoadd_zafe_error(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  PassphraseCheck dco_decode_passphrase_check(dynamic raw);

  @protected
  PaymentInfo dco_decode_payment_info(dynamic raw);

  @protected
  PaymentInput dco_decode_payment_input(dynamic raw);

  @protected
  ProposalInfo dco_decode_proposal_info(dynamic raw);

  @protected
  ProposalList dco_decode_proposal_list(dynamic raw);

  @protected
  ProposalStage dco_decode_proposal_stage(dynamic raw);

  @protected
  ReceivedInfo dco_decode_received_info(dynamic raw);

  @protected
  RecoveryCode dco_decode_recovery_code(dynamic raw);

  @protected
  RecoveryCodeInfo dco_decode_recovery_code_info(dynamic raw);

  @protected
  RecoveryProgress dco_decode_recovery_progress(dynamic raw);

  @protected
  RecoveryStage dco_decode_recovery_stage(dynamic raw);

  @protected
  RepairInfo dco_decode_repair_info(dynamic raw);

  @protected
  ReviewInfo dco_decode_review_info(dynamic raw);

  @protected
  ScannedPayment dco_decode_scanned_payment(dynamic raw);

  @protected
  ScannedRequest dco_decode_scanned_request(dynamic raw);

  @protected
  SeatMove dco_decode_seat_move(dynamic raw);

  @protected
  SendProgress dco_decode_send_progress(dynamic raw);

  @protected
  SendStage dco_decode_send_stage(dynamic raw);

  @protected
  SignerName dco_decode_signer_name(dynamic raw);

  @protected
  TorState dco_decode_tor_state(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  UnapprovedSpendInfo dco_decode_unapproved_spend_info(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  VaultActivity dco_decode_vault_activity(dynamic raw);

  @protected
  VaultActivityKind dco_decode_vault_activity_kind(dynamic raw);

  @protected
  VaultSummary dco_decode_vault_summary(dynamic raw);

  @protected
  ZafeEndpoint dco_decode_zafe_endpoint(dynamic raw);

  @protected
  ZafeError dco_decode_zafe_error(dynamic raw);

  @protected
  ZafeErrorKind dco_decode_zafe_error_kind(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<MempoolEvent> sse_decode_StreamSink_mempool_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<SendProgress> sse_decode_StreamSink_send_progress_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<VaultActivity> sse_decode_StreamSink_vault_activity_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AddressCheck sse_decode_address_check(SseDeserializer deserializer);

  @protected
  ApproveResult sse_decode_approve_result(SseDeserializer deserializer);

  @protected
  Balance sse_decode_balance(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  ZafeError sse_decode_box_autoadd_zafe_error(SseDeserializer deserializer);

  @protected
  ExportedBackup sse_decode_exported_backup(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  IdentityInfo sse_decode_identity_info(SseDeserializer deserializer);

  @protected
  ImportedVault sse_decode_imported_vault(SseDeserializer deserializer);

  @protected
  InviteInfo sse_decode_invite_info(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<PaymentInfo> sse_decode_list_payment_info(SseDeserializer deserializer);

  @protected
  List<PaymentInput> sse_decode_list_payment_input(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ProposalInfo> sse_decode_list_proposal_info(
    SseDeserializer deserializer,
  );

  @protected
  List<ReceivedInfo> sse_decode_list_received_info(
    SseDeserializer deserializer,
  );

  @protected
  List<RepairInfo> sse_decode_list_repair_info(SseDeserializer deserializer);

  @protected
  List<ScannedPayment> sse_decode_list_scanned_payment(
    SseDeserializer deserializer,
  );

  @protected
  List<SeatMove> sse_decode_list_seat_move(SseDeserializer deserializer);

  @protected
  List<SignerName> sse_decode_list_signer_name(SseDeserializer deserializer);

  @protected
  List<UnapprovedSpendInfo> sse_decode_list_unapproved_spend_info(
    SseDeserializer deserializer,
  );

  @protected
  MembershipInfo sse_decode_membership_info(SseDeserializer deserializer);

  @protected
  MempoolEvent sse_decode_mempool_event(SseDeserializer deserializer);

  @protected
  MempoolStatus sse_decode_mempool_status(SseDeserializer deserializer);

  @protected
  MyVote sse_decode_my_vote(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  ZafeError? sse_decode_opt_box_autoadd_zafe_error(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  PassphraseCheck sse_decode_passphrase_check(SseDeserializer deserializer);

  @protected
  PaymentInfo sse_decode_payment_info(SseDeserializer deserializer);

  @protected
  PaymentInput sse_decode_payment_input(SseDeserializer deserializer);

  @protected
  ProposalInfo sse_decode_proposal_info(SseDeserializer deserializer);

  @protected
  ProposalList sse_decode_proposal_list(SseDeserializer deserializer);

  @protected
  ProposalStage sse_decode_proposal_stage(SseDeserializer deserializer);

  @protected
  ReceivedInfo sse_decode_received_info(SseDeserializer deserializer);

  @protected
  RecoveryCode sse_decode_recovery_code(SseDeserializer deserializer);

  @protected
  RecoveryCodeInfo sse_decode_recovery_code_info(SseDeserializer deserializer);

  @protected
  RecoveryProgress sse_decode_recovery_progress(SseDeserializer deserializer);

  @protected
  RecoveryStage sse_decode_recovery_stage(SseDeserializer deserializer);

  @protected
  RepairInfo sse_decode_repair_info(SseDeserializer deserializer);

  @protected
  ReviewInfo sse_decode_review_info(SseDeserializer deserializer);

  @protected
  ScannedPayment sse_decode_scanned_payment(SseDeserializer deserializer);

  @protected
  ScannedRequest sse_decode_scanned_request(SseDeserializer deserializer);

  @protected
  SeatMove sse_decode_seat_move(SseDeserializer deserializer);

  @protected
  SendProgress sse_decode_send_progress(SseDeserializer deserializer);

  @protected
  SendStage sse_decode_send_stage(SseDeserializer deserializer);

  @protected
  SignerName sse_decode_signer_name(SseDeserializer deserializer);

  @protected
  TorState sse_decode_tor_state(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  UnapprovedSpendInfo sse_decode_unapproved_spend_info(
    SseDeserializer deserializer,
  );

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  VaultActivity sse_decode_vault_activity(SseDeserializer deserializer);

  @protected
  VaultActivityKind sse_decode_vault_activity_kind(
    SseDeserializer deserializer,
  );

  @protected
  VaultSummary sse_decode_vault_summary(SseDeserializer deserializer);

  @protected
  ZafeEndpoint sse_decode_zafe_endpoint(SseDeserializer deserializer);

  @protected
  ZafeError sse_decode_zafe_error(SseDeserializer deserializer);

  @protected
  ZafeErrorKind sse_decode_zafe_error_kind(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_mempool_event_Sse(
    RustStreamSink<MempoolEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_send_progress_Sse(
    RustStreamSink<SendProgress> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_vault_activity_Sse(
    RustStreamSink<VaultActivity> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_address_check(AddressCheck self, SseSerializer serializer);

  @protected
  void sse_encode_approve_result(ApproveResult self, SseSerializer serializer);

  @protected
  void sse_encode_balance(Balance self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_zafe_error(
    ZafeError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_exported_backup(
    ExportedBackup self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_identity_info(IdentityInfo self, SseSerializer serializer);

  @protected
  void sse_encode_imported_vault(ImportedVault self, SseSerializer serializer);

  @protected
  void sse_encode_invite_info(InviteInfo self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_payment_info(
    List<PaymentInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_payment_input(
    List<PaymentInput> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_proposal_info(
    List<ProposalInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_received_info(
    List<ReceivedInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_repair_info(
    List<RepairInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_scanned_payment(
    List<ScannedPayment> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_seat_move(List<SeatMove> self, SseSerializer serializer);

  @protected
  void sse_encode_list_signer_name(
    List<SignerName> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_unapproved_spend_info(
    List<UnapprovedSpendInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_membership_info(
    MembershipInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mempool_event(MempoolEvent self, SseSerializer serializer);

  @protected
  void sse_encode_mempool_status(MempoolStatus self, SseSerializer serializer);

  @protected
  void sse_encode_my_vote(MyVote self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_zafe_error(
    ZafeError? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_passphrase_check(
    PassphraseCheck self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_payment_info(PaymentInfo self, SseSerializer serializer);

  @protected
  void sse_encode_payment_input(PaymentInput self, SseSerializer serializer);

  @protected
  void sse_encode_proposal_info(ProposalInfo self, SseSerializer serializer);

  @protected
  void sse_encode_proposal_list(ProposalList self, SseSerializer serializer);

  @protected
  void sse_encode_proposal_stage(ProposalStage self, SseSerializer serializer);

  @protected
  void sse_encode_received_info(ReceivedInfo self, SseSerializer serializer);

  @protected
  void sse_encode_recovery_code(RecoveryCode self, SseSerializer serializer);

  @protected
  void sse_encode_recovery_code_info(
    RecoveryCodeInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_recovery_progress(
    RecoveryProgress self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_recovery_stage(RecoveryStage self, SseSerializer serializer);

  @protected
  void sse_encode_repair_info(RepairInfo self, SseSerializer serializer);

  @protected
  void sse_encode_review_info(ReviewInfo self, SseSerializer serializer);

  @protected
  void sse_encode_scanned_payment(
    ScannedPayment self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_scanned_request(
    ScannedRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_seat_move(SeatMove self, SseSerializer serializer);

  @protected
  void sse_encode_send_progress(SendProgress self, SseSerializer serializer);

  @protected
  void sse_encode_send_stage(SendStage self, SseSerializer serializer);

  @protected
  void sse_encode_signer_name(SignerName self, SseSerializer serializer);

  @protected
  void sse_encode_tor_state(TorState self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unapproved_spend_info(
    UnapprovedSpendInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_vault_activity(VaultActivity self, SseSerializer serializer);

  @protected
  void sse_encode_vault_activity_kind(
    VaultActivityKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_vault_summary(VaultSummary self, SseSerializer serializer);

  @protected
  void sse_encode_zafe_endpoint(ZafeEndpoint self, SseSerializer serializer);

  @protected
  void sse_encode_zafe_error(ZafeError self, SseSerializer serializer);

  @protected
  void sse_encode_zafe_error_kind(ZafeErrorKind self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
