// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Where this device keeps its own copy of every vault's log (spec §6.3, §14). Call it
/// once at startup, in every isolate that talks to the relay, before anything else: the
/// copy is what lets the app notice a relay that lost or rewound the log, so a relay
/// client made before this runs has no such protection.
void initLogCache({required String dir}) =>
    RustLib.instance.api.crateApiAppInitLogCache(dir: dir);
