// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `at`, `invalid`, `net_kind`, `new`, `version_kind`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`

/// Which server an error came from, when it came from one.
enum ZafeEndpoint { none, relay, lightwalletd }

class ZafeError implements FrbException {
  final ZafeErrorKind kind;
  final String message;
  final ZafeEndpoint endpoint;

  const ZafeError({
    required this.kind,
    required this.message,
    required this.endpoint,
  });

  @override
  int get hashCode => kind.hashCode ^ message.hashCode ^ endpoint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ZafeError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          message == other.message &&
          endpoint == other.endpoint;
}

enum ZafeErrorKind {
  /// The relay or lightwalletd could not be reached (`endpoint` says which).
  network,

  /// Waiting on other members or on sync; try again later.
  notReady,

  /// Other members did not answer in time; safe to retry.
  timeout,

  /// This device's independent check failed: never approve or sign.
  verification,

  /// The vault cannot cover the amount plus the fee.
  insufficientFunds,

  /// The vault holds enough, but part of it is held by open proposals.
  fundsReserved,

  /// Bad address, amount, memo or invite.
  invalidInput,

  /// Data, a message or the relay comes from a newer version of Zafe: update the app.
  updateRequired,

  /// The relay is older than this app and must be updated by whoever runs it.
  relayOutdated,

  /// The relay's storage quota for this vault is full; it frees up as old messages
  /// expire (30 days), or whoever runs the relay raises it.
  relayStorageFull,

  /// The TLS handshake with `endpoint` failed (certificate untrusted, expired or for
  /// another host, or a server that doesn't speak TLS).
  tls,

  /// `endpoint` accepted the connection but didn't answer in time.
  networkTimeout,

  /// lightwalletd's chain is behind blocks this wallet already has.
  serverBehind,

  /// lightwalletd serves another network than the vault's.
  wrongNetwork,

  /// This device's wallet database failed (it is a cache: it resyncs if deleted).
  walletDatabase,

  /// "Use Tor" is on and Tor is still connecting: nothing was sent (never direct).
  torConnecting,

  /// "Use Tor" is on but Tor couldn't connect: nothing was sent (never direct).
  torFailed,

  /// The relay answered 404 "unknown mailbox": this vault isn't on the relay used.
  vaultNotOnRelay,
  other,
}
