// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// The latest price of 1 ZEC in USD.
Future<double> zecUsdPrice() => RustLib.instance.api.crateApiPriceZecUsdPrice();
