// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Restores the vault's log on the relay from this phone's copy: recreates the vault
/// after a wiped relay, or appends the entries a rewound relay lost. Returns how many log
/// entries were put back (0: the relay already had everything this phone has). Refuses a
/// relay whose history differs from this phone's copy (`RelayForked`). Messages that were
/// in flight (signing requests) are not restored: members are asked again. Re-register
/// the push token afterwards.
Future<int> restoreRelay({
  required String relayUrl,
  required List<int> seeds,
  required List<int> material,
}) => RustLib.instance.api.crateApiRelayLogRestoreRelay(
  relayUrl: relayUrl,
  seeds: seeds,
  material: material,
);
