// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// The vault's spends the log doesn't account for (empty when all is well, or before the
/// first sync). Reads the wallet database `sync_vault` keeps and the vault log; call it
/// after a sync, so the wallet has seen the chain.
Future<List<UnapprovedSpendInfo>> unapprovedSpends({
  required String relayUrl,
  required String dbDir,
  required List<int> dbKey,
  required List<int> seeds,
  required List<int> material,
}) => RustLib.instance.api.crateApiSpendsUnapprovedSpends(
  relayUrl: relayUrl,
  dbDir: dbDir,
  dbKey: dbKey,
  seeds: seeds,
  material: material,
);

/// A transaction that spent vault notes with no matching approved proposal in the log:
/// keys were used outside Zafe (old shares, or compromised phones).
class UnapprovedSpendInfo {
  /// Transaction id (hex, display order).
  final String txid;

  /// 0 while unmined.
  final int minedHeight;

  const UnapprovedSpendInfo({required this.txid, required this.minedHeight});

  @override
  int get hashCode => txid.hashCode ^ minedHeight.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UnapprovedSpendInfo &&
          runtimeType == other.runtimeType &&
          txid == other.txid &&
          minedHeight == other.minedHeight;
}
