// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `identity`, `material`, `network`, `open_wallet`, `remove_wallet_files`, `runtime`, `sent_txs`, `wallet_key`, `wallet_lock`, `wallet_path`

IdentityInfo generateIdentity() =>
    RustLib.instance.api.crateApiVaultGenerateIdentity();

/// The public key (hex) of an identity, e.g. to mark "You" in member lists.
String identityPublicKey({required List<int> seeds}) =>
    RustLib.instance.api.crateApiVaultIdentityPublicKey(seeds: seeds);

InviteInfo parseInvite({required String invite}) =>
    RustLib.instance.api.crateApiVaultParseInvite(invite: invite);

/// Creates a vault mailbox on the relay and returns the invite string to share.
Future<String> createVault({
  required String relayUrl,
  required List<int> seeds,
  required String name,
  required int threshold,
  required int members,
}) => RustLib.instance.api.crateApiVaultCreateVault(
  relayUrl: relayUrl,
  seeds: seeds,
  name: name,
  threshold: threshold,
  members: members,
);

Future<void> joinVault({
  required String relayUrl,
  required List<int> seeds,
  required String invite,
}) => RustLib.instance.api.crateApiVaultJoinVault(
  relayUrl: relayUrl,
  seeds: seeds,
  invite: invite,
);

Future<MembershipInfo> vaultMembership({
  required String relayUrl,
  required List<int> seeds,
  required String invite,
}) => RustLib.instance.api.crateApiVaultVaultMembership(
  relayUrl: relayUrl,
  seeds: seeds,
  invite: invite,
);

/// Creator only: freezes membership once everyone has joined.
Future<void> sealVault({
  required String relayUrl,
  required List<int> seeds,
  required String invite,
}) => RustLib.instance.api.crateApiVaultSealVault(
  relayUrl: relayUrl,
  seeds: seeds,
  invite: invite,
);

/// Runs key generation. Blocks until every member finishes (or `timeout_secs`). Returns the
/// vault material (secret: store it in secure storage). The creator picks the birthday:
/// `birthday_height`, or lightwalletd's tip + 1 when `None` (the app passes `None`).
/// Then publishes this member's one-tap commitment pool (nonces in `state_dir`, the
/// vault's signing state dir): every member is present at keygen, so every pool is in the
/// log before anyone can propose, and the first payment is one tap. `None` skips it (the
/// pool then waits for the first `list_proposals`); the app always passes the dir.
Future<Uint8List> runKeygen({
  required String relayUrl,
  required String lightwalletdUrl,
  required String networkName,
  required List<int> seeds,
  required String invite,
  required String confirmedSafetyNumber,
  required int timeoutSecs,
  int? birthdayHeight,
  int? expiryDays,
  String? stateDir,
}) => RustLib.instance.api.crateApiVaultRunKeygen(
  relayUrl: relayUrl,
  lightwalletdUrl: lightwalletdUrl,
  networkName: networkName,
  seeds: seeds,
  invite: invite,
  confirmedSafetyNumber: confirmedSafetyNumber,
  timeoutSecs: timeoutSecs,
  birthdayHeight: birthdayHeight,
  expiryDays: expiryDays,
  stateDir: stateDir,
);

VaultSummary vaultSummary({required List<int> material}) =>
    RustLib.instance.api.crateApiVaultVaultSummary(material: material);

/// The vault's unified full viewing key (for auditors): it reveals every past and future
/// payment of the vault but can't spend. Derived from this member's material and checked
/// against the descriptor every member signed.
String vaultViewingKey({required List<int> material}) =>
    RustLib.instance.api.crateApiVaultVaultViewingKey(material: material);

/// The chain tip lightwalletd reports: one cheap call. The app runs `sync_vault` only
/// when it moved since the last successful sync (or when something else changed).
Future<int> chainTip({required String lightwalletdUrl}) => RustLib.instance.api
    .crateApiVaultChainTip(lightwalletdUrl: lightwalletdUrl);

/// Syncs the vault wallet (creating its database under `db_dir` on first use), then holds
/// back the notes that live proposals spend, so `spendable_zat` is what a new proposal can
/// use. Holds are best effort: if the relay can't be reached, the previous ones stay.
Future<Balance> syncVault({
  required String dbDir,
  required List<int> dbKey,
  required String lightwalletdUrl,
  required String relayUrl,
  required List<int> seeds,
  required List<int> material,
}) => RustLib.instance.api.crateApiVaultSyncVault(
  dbDir: dbDir,
  dbKey: dbKey,
  lightwalletdUrl: lightwalletdUrl,
  relayUrl: relayUrl,
  seeds: seeds,
  material: material,
);

/// Registers this device's push token (FCM on Android, APNs on iOS) for the vault, so the
/// relay can wake it on vault activity. Pushes carry no content.
Future<void> registerPush({
  required String relayUrl,
  required List<int> seeds,
  required List<int> material,
  required String platform,
  required String token,
}) => RustLib.instance.api.crateApiVaultRegisterPush(
  relayUrl: relayUrl,
  seeds: seeds,
  material: material,
  platform: platform,
  token: token,
);

class Balance {
  final int height;
  final BigInt spendableZat;

  /// Held for open or sent payments until they're mined or expire.
  final BigInt lockedZat;

  /// The vault's own change from a payment, waiting for confirmations.
  final BigInt changePendingZat;

  /// Received money waiting for confirmations.
  final BigInt incomingPendingZat;
  final BigInt totalZat;

  const Balance({
    required this.height,
    required this.spendableZat,
    required this.lockedZat,
    required this.changePendingZat,
    required this.incomingPendingZat,
    required this.totalZat,
  });

  @override
  int get hashCode =>
      height.hashCode ^
      spendableZat.hashCode ^
      lockedZat.hashCode ^
      changePendingZat.hashCode ^
      incomingPendingZat.hashCode ^
      totalZat.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Balance &&
          runtimeType == other.runtimeType &&
          height == other.height &&
          spendableZat == other.spendableZat &&
          lockedZat == other.lockedZat &&
          changePendingZat == other.changePendingZat &&
          incomingPendingZat == other.incomingPendingZat &&
          totalZat == other.totalZat;
}

/// A new member identity. `seeds` (versioned, see `IdentitySeeds::to_bytes`) is secret:
/// store it in secure storage.
class IdentityInfo {
  final Uint8List seeds;
  final String publicKeyHex;

  const IdentityInfo({required this.seeds, required this.publicKeyHex});

  @override
  int get hashCode => seeds.hashCode ^ publicKeyHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IdentityInfo &&
          runtimeType == other.runtimeType &&
          seeds == other.seeds &&
          publicKeyHex == other.publicKeyHex;
}

class InviteInfo {
  /// The vault's id (hex), known from the invite onward; keys the vault on the device.
  final String vaultId;
  final String name;
  final int threshold;
  final int members;
  final String creatorHex;

  const InviteInfo({
    required this.vaultId,
    required this.name,
    required this.threshold,
    required this.members,
    required this.creatorHex,
  });

  @override
  int get hashCode =>
      vaultId.hashCode ^
      name.hashCode ^
      threshold.hashCode ^
      members.hashCode ^
      creatorHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InviteInfo &&
          runtimeType == other.runtimeType &&
          vaultId == other.vaultId &&
          name == other.name &&
          threshold == other.threshold &&
          members == other.members &&
          creatorHex == other.creatorHex;
}

class MembershipInfo {
  final List<String> members;
  final bool sealed;
  final String safetyNumber;
  final bool isCreator;

  const MembershipInfo({
    required this.members,
    required this.sealed,
    required this.safetyNumber,
    required this.isCreator,
  });

  @override
  int get hashCode =>
      members.hashCode ^
      sealed.hashCode ^
      safetyNumber.hashCode ^
      isCreator.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MembershipInfo &&
          runtimeType == other.runtimeType &&
          members == other.members &&
          sealed == other.sealed &&
          safetyNumber == other.safetyNumber &&
          isCreator == other.isCreator;
}

class VaultSummary {
  final String vaultId;
  final String name;
  final String network;
  final String address;
  final int threshold;
  final List<String> members;
  final int birthdayHeight;

  const VaultSummary({
    required this.vaultId,
    required this.name,
    required this.network,
    required this.address,
    required this.threshold,
    required this.members,
    required this.birthdayHeight,
  });

  @override
  int get hashCode =>
      vaultId.hashCode ^
      name.hashCode ^
      network.hashCode ^
      address.hashCode ^
      threshold.hashCode ^
      members.hashCode ^
      birthdayHeight.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultSummary &&
          runtimeType == other.runtimeType &&
          vaultId == other.vaultId &&
          name == other.name &&
          network == other.network &&
          address == other.address &&
          threshold == other.threshold &&
          members == other.members &&
          birthdayHeight == other.birthdayHeight;
}
