import 'package:flutter/widgets.dart';
import 'package:flutter_svg/flutter_svg.dart';

import '../theme/app_theme.dart';
import 'app_loading_icon.dart';

/// Name-based handles for every design-system icon.
///
/// Keeping the asset paths behind typed constants means a rename only touches
/// this file; call sites reference `AppIcons.book` instead of a string literal.
///
/// Every icon is drawn in the Patina two-tone style (docs/brand.md §4) from
/// Phosphor Icons (MIT), generated by `scripts/brand/patina_icons.py` into
/// `assets/icons/patina/<name>{,_active}.svg`; add a name there (its `MAP`) and
/// here together. The exceptions are [marks] (third-party marks drawn as they
/// are, from `assets/icons/<name>.svg`) and [loader] (code-drawn).
abstract final class AppIcons {
  static const addNew = 'add_new';
  static const arrowDown = 'arrow_down';
  static const arrowDownCircle = 'arrow_down_circle';
  static const book = 'book';
  static const cameraDenied = 'camera_denied';
  static const cancel = 'cancel';
  static const check = 'check';
  static const checkCircle = 'check_circle';
  static const chevronBackward = 'chevron_backward';
  static const chevronForward = 'chevron_forward';
  static const cog = 'cog';
  static const copy = 'copy';
  static const cross = 'cross';
  static const day = 'day';
  static const edit = 'edit';
  static const editFilled = 'edit_filled';
  static const endpoint = 'endpoint';
  static const eye = 'eye';
  static const eyeClosed = 'eye_closed';
  static const globe = 'globe';
  static const help = 'help';
  static const history = 'history';
  static const home = 'home';
  static const importWallet = 'import_wallet';
  static const key = 'key';
  static const link = 'link';
  static const loader = 'loader';
  static const lock = 'lock';
  static const monitor = 'monitor';
  static const night = 'night';
  static const plane = 'plane';
  static const plus = 'plus';
  static const qr = 'qr';
  static const renew = 'renew';
  static const share = 'share';
  static const shieldKeyhole = 'shield_keyhole';
  static const sound = 'sound';
  static const soundOff = 'sound_off';
  static const theme = 'theme';
  static const time = 'time';
  static const tor = 'tor';
  static const trash = 'trash';
  static const unlock = 'unlock';
  static const user = 'user';
  static const users = 'users';
  static const wallet = 'wallet';
  static const warning = 'warning';
  static const warningCircle = 'warning_circle';
  static const zcashCurrency = 'zcash_currency';

  /// Third-party marks kept as their own single-colour glyph (the Zcash
  /// currency symbol): `assets/icons/<name>.svg`, tinted, never two-tone.
  static const marks = {zcashCurrency};
}

/// Renders a Patina two-tone icon from `assets/icons/patina/`: idle, a rounded
/// 1.7 px outline in [color] with closed shapes filled with [patina] (default:
/// the brand accent) at 38%; [active], the solid Phosphor fill in [color] (pass
/// the accent: current tab, a payment that needs you). [AppIcons.marks] render
/// their own glyph tinted with [color] (`BlendMode.srcIn`). [AppIcons.loader] is
/// code-drawn so it can animate while keeping the same call pattern.
///
/// Color resolution order, first non-null wins:
/// 1. Explicit [color] argument at the call site.
/// 2. `IconTheme.of(context).color` — ambient theme. This is what lets
///    a widget like [AppButton] merge its label color into an
///    `IconTheme` wrapper and have every `AppIcon` child pick it up
///    without the caller having to thread the color through.
/// 3. [AppColors.icon.regular] from the ambient [AppTheme] — default
///    "neutral icon" when no other context has spoken.
class AppIcon extends StatelessWidget {
  const AppIcon(
    this.name, {
    this.size = AppIconSize.medium,
    this.color,
    this.animated = true,
    this.semanticLabel,
    this.active = false,
    this.patina,
    super.key,
  });

  /// Draw the solid (filled) form, for state.
  final bool active;

  /// Colour of the closed shapes (drawn at 38%). Defaults to the brand accent,
  /// or to [color] when that is a semantic colour (warning, error, value).
  final Color? patina;

  /// Pass a constant from [AppIcons] — e.g. `AppIcons.book`.
  final String name;

  /// Rendered pixel size (width == height). Defaults to
  /// [AppIconSize.medium] (16); use [AppIconSize.large] (24) for the
  /// asset's native pixel-perfect size.
  final double size;

  /// Tint applied via `BlendMode.srcIn`. When null, falls back through
  /// ambient `IconTheme` and then [AppColors.icon.regular] — see the
  /// class doc for the full resolution order.
  final Color? color;

  /// Controls the pulse animation for [AppIcons.loader]. Ignored by SVG icons.
  final bool animated;

  /// Optional accessibility label forwarded to [SvgPicture.asset].
  final String? semanticLabel;

  @override
  Widget build(BuildContext context) {
    final resolved =
        color ?? IconTheme.of(context).color ?? context.colors.icon.regular;
    if (name == AppIcons.loader) {
      return AppLoadingIcon(
        size: size,
        color: resolved,
        animated: animated,
        semanticLabel: semanticLabel,
      );
    }
    if (!AppIcons.marks.contains(name)) {
      if (active) {
        return SvgPicture.asset(
          'assets/icons/patina/${name}_active.svg',
          width: size,
          height: size,
          colorFilter: ColorFilter.mode(resolved, BlendMode.srcIn),
          semanticsLabel: semanticLabel,
        );
      }
      final fill = patina ?? _defaultPatina(context.colors, resolved);
      return SvgPicture.asset(
        'assets/icons/patina/$name.svg',
        width: size,
        height: size,
        colorMapper: PatinaColorMapper(
          outline: resolved,
          fill: fill.withValues(alpha: fill.a * kPatinaFillOpacity),
        ),
        semanticsLabel: semanticLabel,
      );
    }
    return SvgPicture.asset(
      'assets/icons/$name.svg',
      width: size,
      height: size,
      colorFilter: ColorFilter.mode(resolved, BlendMode.srcIn),
      semanticsLabel: semanticLabel,
    );
  }
}

/// The closed shapes' colour when the caller gives none: an icon drawn in a
/// semantic colour (warning, error, value) keeps that colour, so one icon never
/// mixes two meanings; everything else gets the brand accent.
Color _defaultPatina(AppColors c, Color resolved) {
  final semantic = {
    c.icon.warning,
    c.icon.destructive,
    c.icon.destructiveLight,
    c.icon.value,
    c.text.warning,
    c.text.destructive,
    c.text.destructiveLight,
    c.text.value,
  };
  return semantic.contains(resolved) ? resolved : c.icon.brand;
}

/// Opacity of a Patina icon's closed shapes.
const kPatinaFillOpacity = 0.38;

/// Recolours a Patina SVG: black (#000000) is the outline, magenta (#FF00FF) the
/// closed shapes. Value equality keeps flutter_svg's picture cache working.
@immutable
class PatinaColorMapper extends ColorMapper {
  const PatinaColorMapper({required this.outline, required this.fill});
  final Color outline;
  final Color fill;

  static const _outlineKey = Color(0xFF000000);
  static const _fillKey = Color(0xFFFF00FF);

  @override
  Color substitute(
    String? id,
    String elementName,
    String attributeName,
    Color color,
  ) {
    if (color == _outlineKey) return outline;
    if (color == _fillKey) return fill;
    return color;
  }

  @override
  bool operator ==(Object other) =>
      other is PatinaColorMapper &&
      other.outline == outline &&
      other.fill == fill;

  @override
  int get hashCode => Object.hash(outline, fill);
}
